on:
  push:
    branches: [ main ]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.4'
          tools: phpDocumentor
      - name: Generate documentation 
        run: phpdoc run -d ./src -t ./docmd --template="https://github.com/Saggre/phpDocumentor-markdown/tree/master/themes/markdown"
      - name: Deploy documentation to wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: ${{ github.actor }}@users.noreply.github.com
          ACTION_NAME: ${{ github.actor }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          MD_FOLDER: docmd
          WIKI_PUSH_MESSAGE: Update documentation
          MD_EXTENSION: true
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Add documentation files
        run: git add docmd
      - name: Commit documentation files
        run: git commit -m "Update documentation"
      - name: Push documentation files
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
